#!/bin/bash

# Run this script to make changes visible to the website.

# Usage: USER=<your sunetid> ./push-homeworks
# if [ ! -e /afs ]; then
#  host=$USER@corn.stanford.edu:
# fi

rsync -rvz *.html yxchen@corn.stanford.edu:WWW

